version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - thehive-net

  cortex:
    image: thehiveproject/cortex:3.1.1
    container_name: cortex
    depends_on:
      - elasticsearch
    ports:
      - "9001:9001"
    networks:
      - elasticsearch_thehive-net
    environment:
      - CORTEX_ANALYZERS=/opt/Cortex-Analyzers/analyzers
      - CORTEX_DB_URL=http://elasticsearch:9200
    volumes:
      - cortex_data:/data
      - ./analyzers:/opt/Cortex-Analyzers/analyzers
    networks:
    - thehive-net

volumes:
  esdata:
  cortex_data:

networks:
  thehive-net:
    external: true
